name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve AmaniQuery's documentation!

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      description: What documentation needs improvement?
      placeholder: Describe what documentation is missing, unclear, or incorrect.
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Setup/Installation Guide
        - Contributing Guide
        - Code Comments
        - Module-specific Documentation
        - Examples/Tutorials
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File path(s): [e.g., README.md, docs/SETUP.md]
        - URL (if applicable): [e.g., https://amaniquery.readthedocs.io/...]
        - Section: [e.g., "Quick Start" section in README]

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this documentation be improved?
      placeholder: |
        Provide specific suggestions for improvement. If possible, include:
        - What should be added/changed
        - Why it would be helpful
        - Example content (if applicable)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue
      placeholder: Add any other context, screenshots, or examples here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this documentation issue has not already been reported
          required: true
        - label: I am willing to contribute the documentation improvement myself
          required: false

