name: Feature Request
description: Suggest a new feature or enhancement for AmaniQuery
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make AmaniQuery better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: module
    attributes:
      label: Module Affected
      description: Which module(s) would this feature affect?
      options:
        - Module1_NiruSpider (Web Crawler)
        - Module2_NiruParser (ETL & Embedding)
        - Module3_NiruDB (Vector Database)
        - Module4_NiruAPI (RAG API)
        - Module5_NiruShare (Social Media Sharing)
        - Module6_NiruVoice (Voice Agent)
        - Module7_NiruHybrid (Hybrid RAG)
        - Frontend (Next.js)
        - Android App
        - Documentation
        - Multiple modules
        - New module
        - Not sure
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        Example: "As a [type of user], I want to [goal] so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who would benefit from this feature?
      placeholder: Describe who would benefit and how this feature would improve their experience.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Add any other context, mockups, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have provided all the information requested above
          required: true

